name = "meap-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = false

[node_compat]
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "MEAP_KV", id = "6b70b4869aab4399b2237f1f92f88b58", preview_id = "fa2c5253d4084418a9151b3b9f796b43" }
]

routes = [
  { pattern = "api.meap.fun/*", zone_name = "meap.fun" }
]

[triggers]
crons = ["*/1 * * * *"]


